version: '3.7'

services:
  postgres:
    image: postgres:16.0-alpine3.18
    container_name: 'postgres-go'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"